import jsPDF from 'jspdf';
import { Project, Currency } from '../types';

// ============================================
// PDF STYLES AND CONSTANTS
// ============================================

export const PDF_STYLES = {
    colors: {
        primary: [79, 70, 229] as [number, number, number], // Indigo
        secondary: [16, 185, 129] as [number, number, number], // Emerald
        danger: [239, 68, 68] as [number, number, number], // Red
        warning: [245, 158, 11] as [number, number, number], // Amber
        dark: [15, 23, 42] as [number, number, number], // Slate-900
        medium: [71, 85, 105] as [number, number, number], // Slate-600
        light: [248, 250, 252] as [number, number, number], // Slate-50
        white: [255, 255, 255] as [number, number, number]
    },
    fonts: {
        title: 18,
        subtitle: 14,
        heading: 12,
        normal: 10,
        small: 8
    },
    margins: {
        top: 20,
        bottom: 20,
        left: 14,
        right: 14
    }
};

// ============================================
// HEADER FUNCTIONS
// ============================================

export const addProjectHeader = (
    doc: jsPDF,
    project: Project,
    documentTitle: string,
    documentSubtitle?: string
): number => {
    const { margins, colors, fonts } = PDF_STYLES;

    // Background header
    doc.setFillColor(...colors.primary);
    doc.rect(0, 0, 210, 35, 'F');

    // Logo/App name
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.white);
    doc.text('2 EN 1 APU', margins.left, 12);

    // Document title
    doc.setFontSize(fonts.title);
    doc.text(documentTitle, margins.left, 22);

    // Document subtitle
    if (documentSubtitle) {
        doc.setFontSize(fonts.small);
        doc.setFont('helvetica', 'normal');
        doc.text(documentSubtitle, margins.left, 28);
    }

    // Project info (right side)
    doc.setFontSize(fonts.small);
    doc.setFont('helvetica', 'normal');
    const rightX = 196;
    doc.text(`Proyecto: ${project.code}`, rightX, 12, { align: 'right' });
    doc.text(project.name, rightX, 17, { align: 'right' });

    // Date
    const today = new Date().toLocaleDateString('es-VE', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
    doc.text(today, rightX, 28, { align: 'right' });

    // Reset text color
    doc.setTextColor(0, 0, 0);

    return 40; // Return Y position after header
};

// ============================================
// FOOTER FUNCTIONS
// ============================================

export const addPageFooter = (
    doc: jsPDF,
    pageNumber: number,
    totalPages?: number
): void => {
    const { margins, fonts } = PDF_STYLES;
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(fonts.small);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);

    // Page number
    const pageText = totalPages
        ? `Página ${pageNumber} de ${totalPages}`
        : `Página ${pageNumber}`;
    doc.text(pageText, 105, pageHeight - 10, { align: 'center' });

    // Generated by
    doc.text('Generado por 2 en 1 APU', margins.left, pageHeight - 10);

    // Reset color
    doc.setTextColor(0, 0, 0);
};

// ============================================
// SECTION FUNCTIONS
// ============================================

export const addSectionTitle = (
    doc: jsPDF,
    title: string,
    y: number,
    withBackground: boolean = false
): number => {
    const { margins, colors, fonts } = PDF_STYLES;

    if (withBackground) {
        doc.setFillColor(...colors.light);
        doc.rect(margins.left, y - 5, 182, 8, 'F');
    }

    doc.setFontSize(fonts.heading);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.dark);
    doc.text(title, margins.left, y);

    // Reset
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);

    return y + 8;
};

export const addInfoBox = (
    doc: jsPDF,
    x: number,
    y: number,
    width: number,
    height: number,
    data: { label: string; value: string }[]
): number => {
    const { colors, fonts } = PDF_STYLES;

    // Border
    doc.setDrawColor(...colors.medium);
    doc.rect(x, y, width, height);

    // Content
    let currentY = y + 6;
    doc.setFontSize(fonts.small);

    data.forEach(item => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${item.label}:`, x + 3, currentY);

        doc.setFont('helvetica', 'normal');
        doc.text(item.value, x + 40, currentY);

        currentY += 5;
    });

    return y + height;
};

// ============================================
// SIGNATURE SECTION
// ============================================

export const addSignatureSection = (
    doc: jsPDF,
    y: number
): number => {
    const { margins, fonts } = PDF_STYLES;
    const signatureWidth = 55;
    const signatureHeight = 30;
    const spacing = 6;

    doc.setFontSize(fonts.normal);
    doc.setFont('helvetica', 'bold');
    doc.text('FIRMAS Y AUTORIZACIONES', margins.left, y);

    y += 10;

    // Three signature boxes
    const signatures = [
        { title: 'CONTRATISTA', name: '', position: 'Representante Legal' },
        { title: 'INSPECTOR', name: '', position: 'Inspector de Obra' },
        { title: 'CLIENTE', name: '', position: 'Representante' }
    ];

    signatures.forEach((sig, index) => {
        const x = margins.left + (index * (signatureWidth + spacing));

        // Box
        doc.rect(x, y, signatureWidth, signatureHeight);

        // Title
        doc.setFontSize(fonts.small);
        doc.setFont('helvetica', 'bold');
        doc.text(sig.title, x + signatureWidth / 2, y + signatureHeight + 5, { align: 'center' });

        // Line for signature
        doc.line(x + 3, y + signatureHeight - 8, x + signatureWidth - 3, y + signatureHeight - 8);

        // Position
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(fonts.small - 1);
        doc.text(sig.position, x + signatureWidth / 2, y + signatureHeight + 10, { align: 'center' });
    });

    return y + signatureHeight + 15;
};

// ============================================
// FINANCIAL SUMMARY BOX
// ============================================

export const addFinancialSummary = (
    doc: jsPDF,
    x: number,
    y: number,
    width: number,
    items: { label: string; value: string; type?: 'positive' | 'negative' | 'total' }[],
    currency: Currency
): number => {
    const { colors, fonts } = PDF_STYLES;

    // Border
    doc.setFillColor(...colors.light);
    doc.rect(x, y, width, items.length * 6 + 6, 'F');
    doc.setDrawColor(...colors.medium);
    doc.rect(x, y, width, items.length * 6 + 6);

    let currentY = y + 5;
    doc.setFontSize(fonts.normal);

    items.forEach(item => {
        // Label
        doc.setFont('helvetica', item.type === 'total' ? 'bold' : 'normal');
        doc.text(item.label, x + 3, currentY);

        // Value with color
        if (item.type === 'positive') {
            doc.setTextColor(...colors.secondary);
        } else if (item.type === 'negative') {
            doc.setTextColor(...colors.danger);
        } else if (item.type === 'total') {
            doc.setTextColor(...colors.primary);
            doc.setFont('helvetica', 'bold');
        }

        doc.text(item.value, x + width - 3, currentY, { align: 'right' });

        // Reset color
        doc.setTextColor(0, 0, 0);

        currentY += 6;
    });

    return y + items.length * 6 + 10;
};

// ============================================
// UTILITY FUNCTIONS
// ============================================

export const checkPageBreak = (
    doc: jsPDF,
    currentY: number,
    requiredSpace: number = 40
): number => {
    const pageHeight = doc.internal.pageSize.height;
    const bottomMargin = PDF_STYLES.margins.bottom;

    if (currentY + requiredSpace > pageHeight - bottomMargin) {
        doc.addPage();
        return PDF_STYLES.margins.top;
    }

    return currentY;
};

export const formatCurrencyForPDF = (amount: number, currency: Currency): string => {
    const formatted = amount.toLocaleString('es-VE', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    });

    return currency === 'USD' ? `$${formatted}` : `Bs. ${formatted}`;
};

export const formatDateForPDF = (date: Date): string => {
    return new Date(date).toLocaleDateString('es-VE', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};
